several patches from sourceforge

diff --git a/src/configure.in b/src/configure.in
--- a/src/configure.in
+++ b/src/configure.in
@@ -42,6 +42,8 @@ AC_ARG_ENABLE(setuid,   [  --enable-setuid         install as setuid (linux)],
     setuid=$enableval)
 AC_ARG_ENABLE(fftw,     [  --enable-fftw           use FFTW package],
     fftw=$enableval)
+AC_ARG_ENABLE(fat,              [  --disable-fat    build fat binary on Mac OS X], 
+    fat=$enableval, fat="yes")
 
 dnl Checks for programs.
 AC_PROG_CC
@@ -77,7 +79,7 @@ AC_CHECK_LIB(ffm, sin,PDLIB="$PDLIB -lffm")
 
 dnl Checking for `sin' function in -lm:
 AC_CHECK_LIB(m, sin,PDLIB="$PDLIB -lm",
-	         echo "math library required" || exit 1)
+                 echo "math library required" || exit 1)
 
 dnl Checking for `pthread_create' function in -pthread
 AC_CHECK_LIB(pthread, pthread_create,PDLIB="$PDLIB -lpthread",
@@ -87,7 +89,7 @@ AC_CHECK_LIB(pthread, pthread_create,PDLIB="$PDLIB -lpthread",
          echo "pthreads required"; exit 1))))
 
 dnl Check for fftw package
-if test x$fftw == "xyes";
+if test x$fftw = "xyes";
 then
 AC_CHECK_LIB(fftw, fftw_one,PDLIB="$PDLIB -lfftw",
     echo "fftw package not found - using built-in FFT"; fftw=no)
@@ -96,83 +98,83 @@ fi
 dnl look for tcl 8.x... do I really have to go through all this!?
 
 foundit=no
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl.h,foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl8.7/tcl.h,
-    	GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.7";foundit=yes,)
+        GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.7";foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl8.6/tcl.h,
-    	GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.6";foundit=yes,)
+        GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.6";foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl8.5/tcl.h,
-    	GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.5";foundit=yes,)
+        GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.5";foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl8.4/tcl.h,
-    	GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.4";foundit=yes,)
+        GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.4";foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl8.4/tcl.h,
-    	GUIFLAGS="$GUIFLAGS -I/usr/local/include/tcl8.4";foundit=yes,)
+        GUIFLAGS="$GUIFLAGS -I/usr/local/include/tcl8.4";foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl8.3/tcl.h,
-    	GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.3";foundit=yes,)
+        GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.3";foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     AC_CHECK_HEADER(tcl8.2/tcl.h,
-    	GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.2";foundit=yes,)
+        GUIFLAGS="$GUIFLAGS -I/usr/include/tcl8.2";foundit=yes,)
 fi
-if test $foundit == "no";
+if test $foundit = "no";
 then
     echo no tcl header found
-	 echo bolding trying without...
+         echo bolding trying without...
 #    exit -1
 fi
 
 AC_CHECK_LIB(tcl85, main,,
-	AC_CHECK_LIB(tcl8.5, main,,
+        AC_CHECK_LIB(tcl8.5, main,,
         AC_CHECK_LIB(tcl84, main,,
-	    AC_CHECK_LIB(tcl8.4, main,,
-		AC_CHECK_LIB(tcl8.3, main,,
-		    AC_CHECK_LIB(tcl8.2, main,,
-        		            AC_CHECK_LIB(tcl8.0, main,,
+            AC_CHECK_LIB(tcl8.4, main,,
+                AC_CHECK_LIB(tcl8.3, main,,
+                    AC_CHECK_LIB(tcl8.2, main,,
+                                    AC_CHECK_LIB(tcl8.0, main,,
                             echo no tcl library found; exit 1)))))))
 
 AC_CHECK_LIB(tk85, main,,
-	AC_CHECK_LIB(tk8.5, main,,
+        AC_CHECK_LIB(tk8.5, main,,
        AC_CHECK_LIB(tk84, main,,
-	    AC_CHECK_LIB(tk8.4, main,,
-		AC_CHECK_LIB(tk8.3, main,,
-		    AC_CHECK_LIB(tk8.2, main,,
-        		            AC_CHECK_LIB(tk8.0, main,,
+            AC_CHECK_LIB(tk8.4, main,,
+                AC_CHECK_LIB(tk8.3, main,,
+                    AC_CHECK_LIB(tk8.2, main,,
+                                    AC_CHECK_LIB(tk8.0, main,,
                             echo no tk library found; exit 1)))))))
 
 
-if test `uname -s` == Linux;
+if test `uname -s` = Linux;
 then
     dnl Ckecking for ALSA
     echo .................... alsa= $alsa
 dnl This should be fixed so Pd can use ALSA shared libraries where appropriate.
-    if test x$alsa == xyes; then
-	AC_CHECK_LIB(asound,snd_pcm_info,PDLIB="$PDLIB -lasound" ; alsa="yes",alsa="no")
+    if test x$alsa = xyes; then
+        AC_CHECK_LIB(asound,snd_pcm_info,PDLIB="$PDLIB -lasound" ; alsa="yes",alsa="no")
     fi
 
     dnl Checking for JACK
 
-    if test x$jack == xyes; then
+    if test x$jack = xyes; then
         AC_CHECK_LIB(rt,shm_open,LIBS="$LIBS -lrt")
         AC_CHECK_LIB(jack,jack_set_xrun_callback,LIBS="$LIBS -ljack";jack=xrun,jack=no)
         AC_CHECK_LIB(jack,jack_set_error_function,LIBS="$LIBS -ljack";jack=yes,jack=no)
@@ -184,69 +186,69 @@ dnl This should be fixed so Pd can use ALSA shared libraries where appropriate.
     fi 
     EXT=pd_linux
     CPPFLAGS="-DDL_OPEN -DPA_USE_OSS -DUNIX -DUNISTD\
-    	-DUSEAPI_OSS \
-	-fno-strict-aliasing"
+        -DUSEAPI_OSS \
+        -fno-strict-aliasing"
     SYSSRC="s_midi_oss.c s_audio_oss.c"
-    if test x$alsa == "xyes";
+    if test x$alsa = "xyes";
     then
-    	SYSSRC=$SYSSRC" s_audio_alsa.c s_audio_alsamm.c s_midi_alsa.c"
-	CPPFLAGS=$CPPFLAGS" -DPA_USE_ALSA -DUSEAPI_ALSA"
-	LDFLAGS=$LDFLAGS" -lasound"
+        SYSSRC=$SYSSRC" s_audio_alsa.c s_audio_alsamm.c s_midi_alsa.c"
+        CPPFLAGS=$CPPFLAGS" -DPA_USE_ALSA -DUSEAPI_ALSA"
+        LDFLAGS=$LDFLAGS" -lasound"
     fi
 
-    if test x$portaudio == "xyes";
+    if test x$portaudio = "xyes";
     then
-    	CPPFLAGS=$CPPFLAGS" -DUSEAPI_PORTAUDIO -DHAVE_SYS_SOUNDCARD_H \
-	-Wno-error \
+        CPPFLAGS=$CPPFLAGS" -DUSEAPI_PORTAUDIO -DHAVE_SYS_SOUNDCARD_H \
+        -Wno-error \
         -I../portaudio/include -I../portaudio/src/common \
-	-I../portaudio/src/os/unix/ \
+        -I../portaudio/src/os/unix/ \
         -I../portmidi/pm_common \
         -I../portmidi/pm_linux"
-	SYSSRC="s_audio_pa.c \
-    	s_audio_pablio.c     \
-	s_audio_paring.c     \
-	../portaudio/src/common/pa_allocation.c  \
-	../portaudio/src/common/pa_converters.c  \
-	../portaudio/src/common/pa_cpuload.c     \
-	../portaudio/src/common/pa_dither.c      \
-	../portaudio/src/common/pa_front.c       \
-	../portaudio/src/common/pa_process.c     \
-	../portaudio/src/common/pa_skeleton.c    \
-	../portaudio/src/common/pa_stream.c      \
-	../portaudio/src/common/pa_trace.c       \
-	../portaudio/src/common/pa_debugprint.c  \
-	../portaudio/src/common/pa_ringbuffer.c  \
-	../portaudio/src/os/unix/pa_unix_hostapis.c \
-	../portaudio/src/os/unix/pa_unix_util.c     \
-	../portaudio/src/hostapi/oss/pa_unix_oss.c "$SYSSRC
-	if test x$alsa == "xyes";
-	then
-    	    SYSSRC="../portaudio/src/hostapi/alsa/pa_linux_alsa.c "$SYSSRC
-	    CPPFLAGS=$CPPFLAGS" -DPA_USE_ALSA"
-	fi
-	if test x$jack == "xyes";
-	then
-    	    SYSSRC="../portaudio/src/hostapi/jack/pa_jack.c "$SYSSRC
-	    CPPFLAGS=$CPPFLAGS" -DPA_USE_JACK"
-	fi
+        SYSSRC="s_audio_pa.c \
+        s_audio_pablio.c     \
+        s_audio_paring.c     \
+        ../portaudio/src/common/pa_allocation.c  \
+        ../portaudio/src/common/pa_converters.c  \
+        ../portaudio/src/common/pa_cpuload.c     \
+        ../portaudio/src/common/pa_dither.c      \
+        ../portaudio/src/common/pa_front.c       \
+        ../portaudio/src/common/pa_process.c     \
+        ../portaudio/src/common/pa_skeleton.c    \
+        ../portaudio/src/common/pa_stream.c      \
+        ../portaudio/src/common/pa_trace.c       \
+        ../portaudio/src/common/pa_debugprint.c  \
+        ../portaudio/src/common/pa_ringbuffer.c  \
+        ../portaudio/src/os/unix/pa_unix_hostapis.c \
+        ../portaudio/src/os/unix/pa_unix_util.c     \
+        ../portaudio/src/hostapi/oss/pa_unix_oss.c "$SYSSRC
+        if test x$alsa = "xyes";
+        then
+            SYSSRC="../portaudio/src/hostapi/alsa/pa_linux_alsa.c "$SYSSRC
+            CPPFLAGS=$CPPFLAGS" -DPA_USE_ALSA"
+        fi
+        if test x$jack = "xyes";
+        then
+            SYSSRC="../portaudio/src/hostapi/jack/pa_jack.c "$SYSSRC
+            CPPFLAGS=$CPPFLAGS" -DPA_USE_JACK"
+        fi
     fi
-    if test x$setuid == "xyes";
+    if test x$setuid = "xyes";
     then
-    	binarymode="-m4755"
+        binarymode="-m4755"
     fi
     STRIPFLAG=-s
     GUINAME="pd-gui"
-    if test x$USE_DEBUG_CFLAGS == "xyes";
+    if test x$USE_DEBUG_CFLAGS = "xyes";
     then
-	MORECFLAGS=$MORECFLAGS" -g"
+        MORECFLAGS=$MORECFLAGS" -g"
     else
-	MORECFLAGS=$MORECFLAGS" -O6 -funroll-loops -fomit-frame-pointer"
+        MORECFLAGS=$MORECFLAGS" -O6 -funroll-loops -fomit-frame-pointer"
     fi
-    if test x$jack == "xyes";
+    if test x$jack = "xyes";
     then
         LDFLAGS=$LDFLAGS" -lrt -ljack"
     fi
-    if test x$jack == "xrun";
+    if test x$jack = "xrun";
     then
         LDFLAGS=$LDFLAGS" -lrt -ljack"
     fi
@@ -255,47 +257,52 @@ dnl This should be fixed so Pd can use ALSA shared libraries where appropriate.
 
 fi
 
-if test `uname -s` == Darwin;
+if test `uname -s` = Darwin;
 then
     LDFLAGS="-Wl -framework CoreAudio \
         -framework AudioUnit -framework AudioToolbox \
         -framework Carbon -framework CoreMIDI"
     EXT=pd_darwin
     CPPFLAGS="-DDL_OPEN -DMACOSX -DUNISTD -I/usr/X11R6/include \
-	-I../portaudio/include -I../portaudio/src/common \
-	-I../portaudio/src/os/mac_osx/ \
-	-I../portmidi/pm_common -I../portmidi/pm_mac \
-	-I../portmidi/porttime \
-	-DUSEAPI_PORTAUDIO -DPA19 -DPA_USE_COREAUDIO -DNEWBUFFER"
+        -I../portaudio/include -I../portaudio/src/common \
+        -I../portaudio/src/os/mac_osx/ \
+        -I../portmidi/pm_common -I../portmidi/pm_mac \
+        -I../portmidi/porttime \
+        -DUSEAPI_PORTAUDIO -DPA19 -DPA_USE_COREAUDIO -DNEWBUFFER"
+    dnl for Mac OS X 10.3 (i.e. < 10.4)
     if test `uname -r` = 7.9.0;
     then
-        MORECFLAGS="-DMACOSX3 -DPA_BIG_ENDIAN -Wno-error"
-    	EXTERNTARGET=d_ppc
-    else
+        fat="no"
+    fi
+    if test "x$fat" == "xyes";
+    then
         MORECFLAGS="-isysroot /Developer/SDKs/MacOSX10.4u.sdk \
             -arch i386 -arch ppc -Wno-error"
-    	EXTERNTARGET=d_fat
+        EXTERNTARGET=d_fat
         LDFLAGS=$LDFLAGS" -arch i386 -arch ppc"
+    else
+        MORECFLAGS="-DMACOSX3 -DPA_BIG_ENDIAN -Wno-error"
+        EXTERNTARGET=d_ppc
     fi
     SYSSRC="s_midi_pm.c s_audio_pa.c \
-    	s_audio_pablio.c     \
-	s_audio_paring.c     \
-	../portaudio/src/common/pa_allocation.c  \
-	../portaudio/src/common/pa_converters.c  \
-	../portaudio/src/common/pa_cpuload.c     \
-	../portaudio/src/common/pa_dither.c      \
-	../portaudio/src/common/pa_front.c       \
-	../portaudio/src/common/pa_process.c     \
-	../portaudio/src/common/pa_skeleton.c    \
-	../portaudio/src/common/pa_stream.c      \
-	../portaudio/src/common/pa_trace.c       \
-	../portaudio/src/common/pa_debugprint.c       \
-	../portaudio/src/common/pa_ringbuffer.c  \
-	../portaudio/src/os/unix/pa_unix_util.c     \
-	../portaudio/src/os/mac_osx/pa_mac_hostapis.c   \
-	../portaudio/src/hostapi/coreaudio/pa_mac_core.c  \
-	../portaudio/src/hostapi/coreaudio/pa_mac_core_blocking.c  \
-	../portaudio/src/hostapi/coreaudio/pa_mac_core_utilities.c  \
+        s_audio_pablio.c     \
+        s_audio_paring.c     \
+        ../portaudio/src/common/pa_allocation.c  \
+        ../portaudio/src/common/pa_converters.c  \
+        ../portaudio/src/common/pa_cpuload.c     \
+        ../portaudio/src/common/pa_dither.c      \
+        ../portaudio/src/common/pa_front.c       \
+        ../portaudio/src/common/pa_process.c     \
+        ../portaudio/src/common/pa_skeleton.c    \
+        ../portaudio/src/common/pa_stream.c      \
+        ../portaudio/src/common/pa_trace.c       \
+        ../portaudio/src/common/pa_debugprint.c       \
+        ../portaudio/src/common/pa_ringbuffer.c  \
+        ../portaudio/src/os/unix/pa_unix_util.c     \
+        ../portaudio/src/os/mac_osx/pa_mac_hostapis.c   \
+        ../portaudio/src/hostapi/coreaudio/pa_mac_core.c  \
+        ../portaudio/src/hostapi/coreaudio/pa_mac_core_blocking.c  \
+        ../portaudio/src/hostapi/coreaudio/pa_mac_core_utilities.c  \
         ../portmidi/pm_mac/pmmac.c \
         ../portmidi/pm_mac/pmmacosxcm.c \
         ../portmidi/pm_common/pmutil.c \
@@ -305,34 +312,34 @@ then
     GUINAME="libPdTcl.dylib"
 
 # find the Tcl/Tk Frameworks
- 	 if test -d "../../Frameworks";
+         if test -d "../../Frameworks";
     then
         # Miller's location
         TCLTK_FRAMEWORKS_PATH="../../Frameworks"
- 	 elif test -d "/Library/Frameworks";
-	 then
+         elif test -d "/Library/Frameworks";
+         then
         # get it from the default install location
         TCLTK_FRAMEWORKS_PATH="/Library/Frameworks"
     else
         # Panther has Tcl here; Tiger has Tcl and Tk here
         TCLTK_FRAMEWORKS_PATH="/System/Library/Frameworks"
-    fi		 
+    fi           
     GUIFLAGS="-F$TCLTK_FRAMEWORKS_PATH -framework Tcl -framework Tk \
         -I$TCLTK_FRAMEWORKS_PATH/Tk.framework/Versions/Current/Headers \
         -I$TCLTK_FRAMEWORKS_PATH/Tcl.framework/Versions/Current/Headers \
         -I$TCLTK_FRAMEWORKS_PATH/Tcl.framework/Versions/8.4/PrivateHeaders"
-    if test x$USE_DEBUG_CFLAGS == "xyes";
+    if test x$USE_DEBUG_CFLAGS = "xyes";
     then
-	MORECFLAGS=$MORECFLAGS" -g"
+        MORECFLAGS=$MORECFLAGS" -g"
     else
-	MORECFLAGS=$MORECFLAGS" -O2"
+        MORECFLAGS=$MORECFLAGS" -O2"
     fi
     OSNUMBER=2
-    if test x$jack == "xyes";
+    if test x$jack = "xyes";
     then
-    	LDFLAGS=$LDFLAGS" -weak_framework Jack"
+        LDFLAGS=$LDFLAGS" -weak_framework Jack"
     fi
-    if test x$jack == "xrun";
+    if test x$jack = "xrun";
     then
         LDFLAGS=$LDFLAGS" -weak_framework Jack"
     fi
@@ -341,35 +348,35 @@ fi
 # only Windows uses ASIO, for the rest, set to blank
 ASIOSRC=
 
-if test `uname -s` == MINGW32_NT-5.0;
+if test `uname -s` = MINGW32_NT-5.0;
 then
     EXT=dll
     MORECFLAGS="-DUSEAPI_PORTAUDIO -DPA19 -DMSW -DPA_NO_DS -DPD_INTERNAL \
         -I../portaudio/include -I../portaudio/src/common \
-	-I../portaudio/src/os/win/ \
+        -I../portaudio/src/os/win/ \
         -mwindows -mms-bitfields "$MORECFLAGS
     PDLIB=$PDLIB" -lwsock32 -lwinmm -lole32 -lstdc++"
 
     SYSSRC="s_audio_pa.c s_audio_pablio.c s_audio_paring.c \
         s_audio_mmio.c s_midi_mmio.c \
-	../portaudio/src/common/pa_allocation.c  \
-	../portaudio/src/common/pa_converters.c  \
-	../portaudio/src/common/pa_cpuload.c     \
-	../portaudio/src/common/pa_dither.c      \
-	../portaudio/src/common/pa_front.c       \
-	../portaudio/src/common/pa_process.c     \
-	../portaudio/src/common/pa_skeleton.c    \
-	../portaudio/src/common/pa_stream.c      \
-	../portaudio/src/common/pa_trace.c       \
-	../portaudio/src/common/pa_debugprint.c       \
-	../portaudio/src/common/pa_ringbuffer.c  \
+        ../portaudio/src/common/pa_allocation.c  \
+        ../portaudio/src/common/pa_converters.c  \
+        ../portaudio/src/common/pa_cpuload.c     \
+        ../portaudio/src/common/pa_dither.c      \
+        ../portaudio/src/common/pa_front.c       \
+        ../portaudio/src/common/pa_process.c     \
+        ../portaudio/src/common/pa_skeleton.c    \
+        ../portaudio/src/common/pa_stream.c      \
+        ../portaudio/src/common/pa_trace.c       \
+        ../portaudio/src/common/pa_debugprint.c       \
+        ../portaudio/src/common/pa_ringbuffer.c  \
         ../portaudio/src/os/win/pa_win_util.c       \
         ../portaudio/src/os/win/pa_win_hostapis.c   \
         ../portaudio/src/os/win/pa_x86_plain_converters.c   \
         ../portaudio/src/hostapi/wmme/pa_win_wmme.c"
-	 ASIOSRC="../portaudio/src/hostapi/asio/iasiothiscallresolver.cpp \
-	 ../portaudio/src/hostapi/pa_asio/asio.cpp ../asio/asio.cpp \
-	 ../asio/asiodrivers.cpp ../asio/asiolist.cpp"
+         ASIOSRC="../portaudio/src/hostapi/asio/iasiothiscallresolver.cpp \
+         ../portaudio/src/hostapi/pa_asio/asio.cpp ../asio/asio.cpp \
+         ../asio/asiodrivers.cpp ../asio/asiolist.cpp"
     STRIPFLAG="--strip-unneeded"
     GUINAME="pdtcl.dll"
     GUIFLAGS=
@@ -377,18 +384,18 @@ fi
 
 # support for jack, on either linux or darwin:
 
-if test x$jack == "xyes";
+if test x$jack = "xyes";
 then
     MORECFLAGS=$MORECFLAGS" -DUSEAPI_JACK"
     SYSSRC=$SYSSRC" s_audio_jack.c"
 fi
-if test x$jack == "xrun";
+if test x$jack = "xrun";
 then
     MORECFLAGS=$MORECFLAGS" -DUSEAPI_JACK -DJACK_XRUN"
     SYSSRC=$SYSSRC" s_audio_jack.c"
 fi
 
-if test x$fftw == "xyes";
+if test x$fftw = "xyes";
 then
     SYSSRC=$SYSSRC" d_fft_fftw.c d_fftroutine.c"
     LDFLAGS=$LDFLAGS" -lfftw"
